### ISSUE TITLE
Swift 5 Infinite Looping

### ISSUE THREAD

**Issue by Jon889** [lucianomarisi/JSONUtilities#31]
I've been updating our app to Swift 5 and had this problem with JSONUtilities' convenience functions for optional values. https://forums.swift.org/t/swift-5-throwing-and-non-throwing-function/28877

It seems like we have 2 options:
1. Keep the convenience methods for optionals (eg like this person has done in their fork https://github.com/Nonouf/JSONUtilities/commit/44e9ab19a0665adb437c7d9c7f44ef5cc0df5359) See PR #33
2. Remove the convenience methods, and user's of the framework with have to use `try?` in their own. See PR #32 

I’m think option 2 is best, as said in the thread linked above, overloading functions on whether it throws isn’t recommended apparently, and it doesn’t even work unless the type signature is different, so it might break again in the future.

**Comment by lucianomarisi** [comment]
Thanks for taking the time to contribute!

I'd personally go with option 1 since some people may rely on the convenience methods. This is the first time there was an issue with this kind of overloading. My suggestion is that If new issues arise from this pattern then we can deprecate the convenience methods and eventually delete them.
